from runner import create_filename_dict
datasets = create_filename_dict("files")

import pandas as pd
import matplotlib.pyplot as plt
fig,ax = plt.subplots(1,1)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
dim_match_summary = datasets['dim_match_summary'].copy()
dim_players = datasets['dim_players'].copy()
fact_bating_summary = datasets['fact_bating_summary'].copy()
fact_bowling_summary = datasets['fact_bowling_summary'].copy()
df = fact_bating_summary.merge(dim_players,left_on='batsmanName',right_on='name').merge(dim_match_summary,left_on='match_id',right_on='match_id')
df['SR'] = df['SR'].str.replace(r'[^\d.]', '0', regex=True).astype(float)
df_bowlers = fact_bowling_summary.merge(dim_players,left_on='bowlerName',right_on='name')
df_bowlers = df_bowlers.groupby('bowlerName')['economy'].mean().reset_index()
df_batters = df.groupby('batsmanName')['SR'].mean().reset_index()
df_batters = df_batters.merge(df_bowlers,left_on='batsmanName',right_on='bowlerName').query('economy > 10')
df_batters = df_batters.sort_values('SR',ascending=False).head(10)
ax.bar(df_batters['batsmanName'],df_batters['SR'])
ax.set_xlabel('Batsman Name')
ax.set_ylabel('Average SR')
ax.set_title('Top 10 Batsmen with Average SR > 10 and Economy > 10')
fig.suptitle('')
plt.show()