[theme]
primaryColor = "#6495ED"        # CornflowerBlue
backgroundColor = "#002147"     # OxfordBlue (Darker shade)
secondaryBackgroundColor = "#4682B4" # SteelBlue (Lighter shade)
textColor = "#E0E0E0"           # Light gray for contrast
font = "sans serif"

[browser]
gatherUsageStats = false
