[theme]
primaryColor = "#1E90FF"        # Primary color changed to DodgerBlue
backgroundColor = "#000080"     # Navy background color
secondaryBackgroundColor = "#00008B" # Darker blue secondary background color
textColor = "#E0E0E0"           # Light gray text color for contrast
font = "sans serif"

[browser]
gatherUsageStats = false
