[theme]
primaryColor = "#1E90FF"        # DodgerBlue
backgroundColor = "#000080"     # Navy
secondaryBackgroundColor = "#00008B" # DarkBlue
textColor = "#E0E0E0"           # Light gray for contrast
font = "sans serif"

[browser]
gatherUsageStats = false
